src/Entity/Homework.php
<?php

namespace App\Entity;

use App\Repository\HomeworkRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HomeworkRepository::class)]
class Homework
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $id_prof = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $datelimite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProf(): ?string
    {
        return $this->id_prof;
    }

    public function setIdProf(string $id_prof): static
    {
        $this->id_prof = $id_prof;

        return $this;
    }

    public function getDatelimite(): ?\DateTimeInterface
    {
        return $this->datelimite;
    }

    public function setDatelimite(\DateTimeInterface $datelimite): static
    {
        $this->datelimite = $datelimite;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/PopupController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface; 
use App\Entity\Homework;

class PopupController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function popupContent(): Response
    {
        $homeworks = $this->entityManager->getRepository(Homework::class)->findAll();

        return $this->render('popup/content.html.twig', [
            'homeworks' => $homeworks,
        ]);
    }
}

templates/popup/content.html.twig
{# templates/popup/content.html.twig #}

<link rel="stylesheet" href="{{ asset('style.css') }}">
<div class="agenda">
    {% for homework in homeworks %}
        {% if homework.idProf == app.session.get('user_name') %}
            <div class="homework">
                <div>
                    <h1>{{ homework.name }}</h1>
                    <h1>{{ homework.idProf }}</h1>
                </div>
                <p>{{ homework.description }}</p>
                <p2>{{ homework.datelimite|date('Y-m-d') }}</p2>
                <a href="{{ path('edit_homework', { 'id': homework.id }) }}"><button >Modifier</button></a>
                <a href="{{ path('delete_homework', { 'id': homework.id }) }}"><button >Supprimer</button></a>
            </div>
        {% endif %}
    {% endfor %}
</div>